### ISSUE TITLE
ci/cd: Automate versioning and releases

### ISSUE THREAD

**Issue by wise-introvert** [wise-introvert/deepsearchjs#1]

**Comment by wise-introvert** [comment]
One possible solution:

```yaml
name: Release and Deploy

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install dependencies
      run: npm ci

    - name: Bump version
      run: |
        # Bump the version in package.json
        npm version patch 

    - name: Publish to npm
      run: |
        # Publish the package to npm
        npm publish
```
This action will run automatically when you push to the main branch. It will bump the version in package.json using npm version patch command, and then it will use npm publish to deploy the package to the npm registry.
Please make sure you have npm token as secret in your repository.

**Comment by wise-introvert** [comment]
Another possible solution ( more control over versions ):
```yaml
name: Release and Deploy

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      VERSION_TYPE: ${{ env.VERSION_TYPE }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14
    - name: Install dependencies
      run: npm ci
    - name: Bump version
      run: |
        # Bump the version in package.json
        if [ "${{ env.VERSION_TYPE }}" = "patch" ]; then
          npm version patch
        elif [ "${{ env.VERSION_TYPE }}" = "minor" ]; then
          npm version minor
        elif [ "${{ env.VERSION_TYPE }}" = "major" ]; then
          npm version major
        fi
    - name: Publish to npm
      run: |
        # Publish the package to npm
        npm publish
```

This action will run automatically when you push to the main branch. It will take the VERSION_TYPE from the environment variable and use npm version command to bump the version in package.json accordingly and then it will use npm publish to deploy the package to the npm registry. You can trigger the workflow with version type as minor, patch or major and it will bump the package version accordingly.
Please make sure you have npm token as secret in your repository.
